package com.pm.analyticsservice.summarizer;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Primary;
import org.springframework.http.MediaType;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

import java.time.Duration;
import java.util.List;
import java.util.Map;

/**
 * LLM-backed {@link Summarizer} that phrases the month's figures as a short narrative.
 * It speaks the <b>OpenAI-compatible</b> Chat Completions protocol, so the provider is
 * just configuration ({@code finsight.summarizer.ai.base-url} + {@code model}); the
 * default is <b>Groq</b> (free tier). Created only when
 * {@code finsight.summarizer.ai.enabled=true} and marked {@link Primary} so it wins
 * injection over {@link TemplateSummarizer}, which it keeps as the fallback.
 *
 * <p><b>It never fails the request.</b> Any error — timeout, non-2xx, malformed JSON,
 * empty field — is caught and the template answers instead. It sends only AGGREGATED
 * figures and category names (no userId, email, or individual transaction).
 */
@Component
@Primary
@ConditionalOnProperty(prefix = "finsight.summarizer.ai", name = "enabled", havingValue = "true")
public class LlmSummarizer implements Summarizer {

    private static final Logger log = LoggerFactory.getLogger(LlmSummarizer.class);

    private static final String SYSTEM_PROMPT = """
            You write a short, calm personal-finance monthly summary for an end user.
            You are given JSON figures for one month. Respond with a single JSON object: \
            {"summary": string}. Write two or three plain sentences: state the savings rate \
            and whether it rose or fell versus the previous month, and name the largest \
            expense category. Use the provided currency code. Do not invent any number that \
            is not in the input. English only.""";

    private final SummarizerAiProperties props;
    private final TemplateSummarizer fallback;
    private final ObjectMapper objectMapper = new ObjectMapper();
    private final RestClient restClient;
    private final Counter aiSuccess;
    private final Counter aiFallback;

    public LlmSummarizer(SummarizerAiProperties props,
                         TemplateSummarizer fallback,
                         MeterRegistry meterRegistry) {
        this.props = props;
        this.fallback = fallback;

        SimpleClientHttpRequestFactory factory = new SimpleClientHttpRequestFactory();
        factory.setConnectTimeout(Duration.ofMillis(props.getTimeoutMs()));
        factory.setReadTimeout(Duration.ofMillis(props.getTimeoutMs()));
        this.restClient = RestClient.builder()
                .baseUrl(props.getBaseUrl())
                .requestFactory(factory)
                .defaultHeader("Authorization", "Bearer " + props.getApiKey())
                .build();

        this.aiSuccess = Counter.builder("finsight.analytics.ai.success")
                .description("Monthly summaries generated by the LLM")
                .register(meterRegistry);
        this.aiFallback = Counter.builder("finsight.analytics.ai.fallback")
                .description("Summaries that fell back to the template after an LLM error")
                .register(meterRegistry);
    }

    @Override
    public FinancialSummary summarize(MonthlySummaryData data) {
        try {
            FinancialSummary summary = callLlm(data);
            aiSuccess.increment();
            return summary;
        } catch (Exception ex) {
            log.warn("LLM summary failed for {}, falling back to template: {}",
                    data.yearMonth(), ex.toString());
            aiFallback.increment();
            return fallback.summarize(data);
        }
    }

    private FinancialSummary callLlm(MonthlySummaryData data) throws Exception {
        // Only aggregated figures + category names are sent — no identity.
        String userPrompt = objectMapper.writeValueAsString(data);

        Map<String, Object> body = Map.of(
                "model", props.getModel(),
                "max_tokens", props.getMaxTokens(),
                "response_format", Map.of("type", "json_object"),
                "messages", List.of(
                        Map.of("role", "system", "content", SYSTEM_PROMPT),
                        Map.of("role", "user", "content", userPrompt)));

        String raw = restClient.post()
                .uri("/chat/completions")
                .contentType(MediaType.APPLICATION_JSON)
                .body(body)
                .retrieve()
                .body(String.class);

        JsonNode root = objectMapper.readTree(raw);
        String contentJson = root.path("choices").path(0).path("message").path("content").asText();
        JsonNode parsed = objectMapper.readTree(contentJson);
        String summary = parsed.path("summary").asText("");

        if (summary.isBlank()) {
            throw new IllegalStateException("LLM returned an empty summary");
        }
        return new FinancialSummary(summary, true);
    }
}
