package com.pm.analyticsservice.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Record that a user's monthly report has been published (Phase G.2).
 *
 * <p>The consumer-side {@code processed_events} inbox de-duplicates events that arrive; this is
 * its producer-side counterpart, because the report is generated by a schedule rather than by an
 * event and so has nothing upstream to key on. Without it, tomorrow's sweep would report last
 * month all over again.
 */
@Entity
@Table(name = "monthly_report_sent")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MonthlyReportSent {

    @Id
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "id", updatable = false, nullable = false, length = 36)
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    /** The month reported on, 'YYYY-MM'. */
    @Column(name = "period_month", nullable = false, length = 7)
    private String periodMonth;

    @Column(name = "sent_at", nullable = false)
    private LocalDateTime sentAt;
}
